![question](img/spring17q2i.png)

In [2]:
import numpy as np
import pandas as pd
import pyquantlib as pq
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline
from importlib import reload

In [9]:
# question given:
mu = np.array([0.046, 0.055, 0.064, 0.073, 0.079]).reshape(-1, 1)
cov_mat = np.array([[0.0625, -0.02, 0.015, -0.01, -0.01],
                    [-0.02, 0.0841, -0.025, -0.03, 0.005],
                    [0.015, -0.025, 0.1024, 0.055, -0.005],
                    [-0.01, -0.03, 0.055, 0.1225, 0.025],
                    [-0.01, 0.005, -0.005, 0.025, 0.1369]])
r = 0.02

![questionii](img/spring17q2ii.png)

#### Part i Tangency Port

In [10]:
mu_bar = mu - r
mu_bar

array([[ 0.026],
       [ 0.035],
       [ 0.044],
       [ 0.053],
       [ 0.059]])

In [11]:
wt = pq.portopt.tangency_port(cov_mat, mu_bar)
wt

array([[ 0.27669849],
       [ 0.30443216],
       [ 0.09934396],
       [ 0.18269862],
       [ 0.13682677]])

#### Part ii Min Var with mu_req

In [16]:
mu_req = 0.06
w, wcash, sigma = pq.portopt.min_var_port(cov_mat, mu, r, mu_req)
print("Weights:\n",w,"\nCash:",wcash, "\nSigma:", sigma)

Weights:
 [[ 0.27686304]
 [ 0.3046132 ]
 [ 0.09940303]
 [ 0.18280727]
 [ 0.13690814]] 
Cash: [[-0.00059468]] 
Sigma: [[ 0.12092953]]


#### Part iii Max Ret with sig_req

In [15]:
sig_req = 0.3
w, wcash, mu_exp = pq.portopt.max_ret_port(cov_mat, mu, r, sig_req)
print("Weights:\n",w,"\nCash:",wcash, "\nExpRet:", mu_exp)

Weights:
 [[ 0.68683733]
 [ 0.75567948]
 [ 0.24659743]
 [ 0.45350529]
 [ 0.33963949]] 
Cash: [[-1.48225902]] 
ExpRet: [[ 0.11923135]]
