In [21]:
import numpy as np
import pandas as pd
import pyquantlib as pq
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline
from importlib import reload

In [23]:
# question given:
mu = np.array([0.026, 0.034, 0.045, 0.052]).reshape(-1, 1)
cov_mat = np.array([[0.04, -0.015, 0.015, -0.005],
                    [-0.015, 0.0625, -0.02, -0.01],
                    [0.015, -0.02, 0.1024, 0.02],
                    [-0.005, -0.01, 0.02, 0.1225]])
r = 0.0075
cov_mat

array([[ 0.04  , -0.015 ,  0.015 , -0.005 ],
       [-0.015 ,  0.0625, -0.02  , -0.01  ],
       [ 0.015 , -0.02  ,  0.1024,  0.02  ],
       [-0.005 , -0.01  ,  0.02  ,  0.1225]])

#### Part i Tangency Port

In [24]:
mu_bar = mu - r
mu_bar

array([[ 0.0185],
       [ 0.0265],
       [ 0.0375],
       [ 0.0445]])

In [25]:
wt = pq.portopt.tangency_port(cov_mat, mu_bar)
wt

array([[ 0.30956108],
       [ 0.35005148],
       [ 0.15662126],
       [ 0.18376619]])

In [26]:
mu

array([[ 0.026],
       [ 0.034],
       [ 0.045],
       [ 0.052]])

In [28]:
wt.transpose().dot(mu)

array([[ 0.03655414]])

In [15]:
# expected return
exp_ret = mu_bar.transpose().dot(wt)[0,0] + r
exp_ret2 = mu.transpose().dot(wt)[0,0]
exp_ret, exp_ret2

(0.036554136646969305, 0.036554136646969299)

In [13]:
# variance
tang_std = np.sqrt(wt.transpose().dot(cov_mat).dot(wt))[0,0]
tang_std

0.11596041568152712

In [30]:
# sharpe
(exp_ret2 - r) / tang_std

0.25055219469688156

#### Part ii Min Var with mu_req

In [31]:
mu_req = 0.04
w, wcash, sigma = pq.portopt.min_var_port(cov_mat, mu, r, mu_req)
print("Weights:\n",w,"\nCash:",wcash, "\nSigma:", sigma)

Weights:
 [[ 0.34627547]
 [ 0.3915681 ]
 [ 0.17519677]
 [ 0.20556113]] 
Cash: [[-0.11860147]] 
Sigma: [[ 0.12971349]]


#### Part iii Max Ret with sig_req

In [32]:
sig_req = 0.28
w, wcash, mu_exp = pq.portopt.max_ret_port(cov_mat, mu, r, sig_req)
print("Weights:\n",w,"\nCash:",wcash, "\nExpRet:", mu_exp)

Weights:
 [[ 0.74747146]
 [ 0.84524027]
 [ 0.37818037]
 [ 0.44372498]] 
Cash: [[-1.41461708]] 
ExpRet: [[ 0.07765461]]
