In [1]:
import numpy as np
import pyquantlib as pq

In [2]:
# question input
cov_mat = np.array([[0.36, 0.0, -0.10, 0.10, 0.05, -0.05],
                   [0.0, 0.64, 0.15, 0.0, 0.15, 0.0],
                   [-0.1, 0.15, 0.81, -0.25, -0.2, -0.05],
                   [0.1, 0.0, -0.25, 1.21, 0.25, -0.35],
                   [0.05, 0.15, -0.2, 0.25, 1, 0.15],
                   [-0.05, 0.0, -0.05, -0.35, 0.15, 1.44]])
cov_mat

array([[ 0.36,  0.  , -0.1 ,  0.1 ,  0.05, -0.05],
       [ 0.  ,  0.64,  0.15,  0.  ,  0.15,  0.  ],
       [-0.1 ,  0.15,  0.81, -0.25, -0.2 , -0.05],
       [ 0.1 ,  0.  , -0.25,  1.21,  0.25, -0.35],
       [ 0.05,  0.15, -0.2 ,  0.25,  1.  ,  0.15],
       [-0.05,  0.  , -0.05, -0.35,  0.15,  1.44]])

### Check

In [12]:
diag = 1 / np.sqrt(np.diag(cov_mat))
D = np.diag(diag)
D

array([[ 1.66666667,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.25      ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.11111111,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.90909091,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.83333333]])

In [13]:
print(D.dot(cov_mat).dot(D))

[[ 1.          0.         -0.18518519  0.15151515  0.08333333 -0.06944444]
 [ 0.          1.          0.20833333  0.          0.1875      0.        ]
 [-0.18518519  0.20833333  1.         -0.25252525 -0.22222222 -0.0462963 ]
 [ 0.15151515  0.         -0.25252525  1.          0.22727273 -0.26515152]
 [ 0.08333333  0.1875     -0.22222222  0.22727273  1.          0.125     ]
 [-0.06944444  0.         -0.0462963  -0.26515152  0.125       1.        ]]


#### Extracting corr matrix and variance

In [4]:
corr_mat, var_list = pq.covariance.extract_var_and_corr(cov_mat)
print(corr_mat)
#print(var_list)

[[ 1.          0.         -0.18518519  0.15151515  0.08333333 -0.06944444]
 [ 0.          1.          0.20833333  0.          0.1875      0.        ]
 [-0.18518519  0.20833333  1.         -0.25252525 -0.22222222 -0.0462963 ]
 [ 0.15151515  0.         -0.25252525  1.          0.22727273 -0.26515152]
 [ 0.08333333  0.1875     -0.22222222  0.22727273  1.          0.125     ]
 [-0.06944444  0.         -0.0462963  -0.26515152  0.125       1.        ]]


In [7]:
# check
diag = 1 / np.sqrt(np.diag(cov_mat))

In [9]:
D = np.diag(diag)
D

array([[ 1.66666667,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  1.25      ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  1.11111111,  0.        ,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.90909091,  0.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.83333333]])

In [11]:
print(D.dot(cov_mat).dot(D))

[[ 1.          0.         -0.18518519  0.15151515  0.08333333 -0.06944444]
 [ 0.          1.          0.20833333  0.          0.1875      0.        ]
 [-0.18518519  0.20833333  1.         -0.25252525 -0.22222222 -0.0462963 ]
 [ 0.15151515  0.         -0.25252525  1.          0.22727273 -0.26515152]
 [ 0.08333333  0.1875     -0.22222222  0.22727273  1.          0.125     ]
 [-0.06944444  0.         -0.0462963  -0.26515152  0.125       1.        ]]


#### Rebuilding the cov matrix from list of variance

In [4]:
cov_rec = pq.covariance.calc_cov_mat(corr_mat, var_list)
cov_rec

array([[ 0.64,  0.15,  0.  ,  0.15,  0.  ],
       [ 0.15,  0.81, -0.25, -0.2 , -0.05],
       [ 0.  , -0.25,  1.21,  0.25, -0.35],
       [ 0.15, -0.2 ,  0.25,  1.  ,  0.15],
       [ 0.  , -0.05, -0.35,  0.15,  1.44]])

#### Rebuilding the cov matrix from list of sd

In [5]:
sd_list = np.sqrt(var_list)
sd_list

array([ 0.8,  0.9,  1.1,  1. ,  1.2])

In [6]:
cov_rec2 = pq.covariance.calc_cov_mat(corr_mat, sd_list, is_sd=True)
cov_rec2

array([[ 0.64,  0.15,  0.  ,  0.15,  0.  ],
       [ 0.15,  0.81, -0.25, -0.2 , -0.05],
       [ 0.  , -0.25,  1.21,  0.25, -0.35],
       [ 0.15, -0.2 ,  0.25,  1.  ,  0.15],
       [ 0.  , -0.05, -0.35,  0.15,  1.44]])