![question](img/var_of_port.png)

In [1]:
import numpy as np
import pandas as pd
import pyquantlib as pq

import matplotlib.pyplot as plt
%matplotlib inline

from importlib import reload

In [2]:
mu = np.array([0.1, 0.12, 0.17]).reshape(-1,1)

sigma = np.array([0.25, 0.3, 0.32])

corr_mat = np.array([[1, 0.25, -0.25],
                    [0.25, 1, 0.5],
                    [-0.25, 0.5, 1]])
D = np.diag(sigma)
cov_mat = D.dot(corr_mat).dot(D)

In [3]:
cov_mat

array([[ 0.0625 ,  0.01875, -0.02   ],
       [ 0.01875,  0.09   ,  0.048  ],
       [-0.02   ,  0.048  ,  0.1024 ]])

### Part i)

In [4]:
corr_mat, var_list = pq.covariance.extract_var_and_corr(cov_mat)
sd_list = np.sqrt(var_list)
sd_list

array([ 0.25,  0.3 ,  0.32])

In [5]:
var_list = []
for sd in sd_list:
    var_list.append(pq.valueatrisk.value_at_risk(10, 0.99, sd) * 100)
print(var_list)

[11.585489726324404, 13.902587671589286, 14.829426849695238]


### Part ii)

### Solving for the tangency portfolios

#### Asset 1 and 2

In [6]:
cov_mat_12 = cov_mat[0:2,0:2]
cov_mat_12

array([[ 0.0625 ,  0.01875],
       [ 0.01875,  0.09   ]])

In [7]:
wt_12 = pq.portopt.min_var_overall_port(cov_mat_12)
wt_12

array([[ 0.61956522],
       [ 0.38043478]])

In [8]:
pq.valueatrisk.value_at_risk_port(10, 0.99, wt_12, cov_mat_12) * 100

array([[ 2.12505586]])

#### Asset 2 and 3

In [9]:
cov_mat_23 = cov_mat[1:3,1:3]
cov_mat_23

array([[ 0.09  ,  0.048 ],
       [ 0.048 ,  0.1024]])

In [10]:
wt_23 = pq.portopt.min_var_overall_port(cov_mat_23)
wt_23

array([[ 0.56431535],
       [ 0.43568465]])

In [11]:
pq.valueatrisk.value_at_risk_port(10, 0.99, wt_23, cov_mat_23) * 100

array([[ 3.32277614]])

#### Asset 1 an 3

In [12]:
cov_mat_13 = cov_mat[0:3:2, 0:3:2]
cov_mat_13

array([[ 0.0625, -0.02  ],
       [-0.02  ,  0.1024]])

In [13]:
wt_13 = pq.portopt.min_var_overall_port(cov_mat_13)
wt_13

array([[ 0.59736457],
       [ 0.40263543]])

In [14]:
pq.valueatrisk.value_at_risk_port(10, 0.99, wt_13, cov_mat_13) * 100

array([[ 1.35701197]])

In [15]:
wt = pq.portopt.min_var_overall_port(cov_mat)
wt

array([[ 0.60783152],
       [-0.02302392],
       [ 0.4151924 ]])

In [16]:
pq.valueatrisk.value_at_risk_port(10, 0.99, wt, cov_mat) * 100

array([[ 1.35568411]])