In [1]:
import numpy as np

In [2]:
A = np.array([[41, 24],
              [24, 136]])

In [3]:
A

array([[ 41,  24],
       [ 24, 136]])

In [5]:
l1 = (177 + np.sqrt(177**2 - 20000)) / 2
l2 = (177 - np.sqrt(177**2 - 20000)) / 2

In [11]:
l1, l2

(141.71888762460185, 35.281112375398152)

In [27]:
q11 = ((l1 - 136) / 24) / (np.sqrt(1 + ((l1 - 136) / 24)**2))
q12 = ((l2 - 136) / 24) / (np.sqrt(1 + ((l2 - 136) / 24)**2))
q21 = 1 / (np.sqrt(1 + ((l1 - 136) / 24)**2))
q22 = 1 / (np.sqrt(1 + ((l2 - 136) / 24)**2))

In [28]:
Q = np.array([[q11, q12],[q21, q22]])

In [30]:
Q

array([[ 0.23179704, -0.97276417],
       [ 0.97276417,  0.23179704]])

In [29]:
np.matmul(Q,Q.transpose())

array([[  1.00000000e+00,  -1.38777878e-16],
       [ -1.38777878e-16,   1.00000000e+00]])

In [31]:
L = np.array([[l1,0],[0,l2]])

In [32]:
L

array([[ 141.71888762,    0.        ],
       [   0.        ,   35.28111238]])

In [33]:
np.matmul(np.matmul(Q,L),Q.transpose())

array([[  41.,   24.],
       [  24.,  136.]])

In [36]:
L_b = np.sqrt(L)

In [38]:
B = np.matmul(np.matmul(Q,L_b),Q.transpose())

In [39]:
np.matmul(B,B)

array([[  41.,   24.],
       [  24.,  136.]])

In [40]:
B

array([[  6.26027764,   1.34496241],
       [  1.34496241,  11.58408719]])

In [45]:
a1 = np.sqrt(41)
b1 = 24 - a1
#d1 = np.sqrt(136 - b1**2)

309.65003660322327

In [46]:
np.sqrt(136)

11.661903789690601

In [47]:
np.sqrt(41)

6.4031242374328485

In [58]:
U = np.array([[np.sqrt(41), 24 / np.sqrt(41)],
              [0, np.sqrt(136 - 576 / 41)]])

In [60]:
np.matmul(U.transpose(),U)

array([[  41.,   24.],
       [  24.,  136.]])

In [61]:
U

array([[  6.40312424,   3.74817029],
       [  0.        ,  11.04315261]])

In [62]:
B

array([[  6.26027764,   1.34496241],
       [  1.34496241,  11.58408719]])