In [1]:
import numpy as np

In [27]:
# simpson's rule
def i_simpson(a, b, n, fofx):
    """
    a = left end point of integration interval
    b = right end point of integration interval
    n = number of partitions
    fofx = a function of x, a single variable
    """
    h = (b - a) / n
    i_cur = fofx(a) / 6 + fofx(b) / 6
    for i in range(1, n): # python's range iterator is exclusive of the right point
        i_cur += fofx(a + i*h) / 3
    for i in range(1, n+1):
        i_cur += 2 * fofx(a + (i - 0.5) * h) / 3
    return h * i_cur

def r_inst(t):
    return 0.04 + 0.01 * (np.log(1 + t))

def r_inst_sub(t):
    return np.log(1 + t)

def r_c(t):
    inner = ((t + 1) * np.log(1 + t)) - t
    mid = 0.04 * t + 0.01 * inner
    return mid / t

def r_c_check(t, n):
    integral = i_simpson(0, t, n, r_inst)
    return integral / t

def r_c_check2(t, n):
    integral = i_simpson(0, t, n, r_inst_sub)
    return (0.04 * t + 0.01 * integral) / t

In [28]:
t_list = np.arange(0, 2.5, 0.5)[1:]
n = 1000
print(t_list)

print(r_c(t_list))
print(r_c_check(t_list, n))
print(r_c_check2(t_list, n))

[ 0.5  1.   1.5  2. ]
[ 0.04216395  0.04386294  0.04527151  0.04647918]
[ 0.04216395  0.04386294  0.04527151  0.04647918]
[ 0.04216395  0.04386294  0.04527151  0.04647918]
