In [2]:
import numpy as np

In [3]:
def r_c(t):
    return 0.05 + 0.005 * np.sqrt(1 + t)

def df(t):
    return np.exp(-r_c(t) * t)

In [4]:
t_list = np.arange(1/12, 20/12, 0.5)[0:]
print(t_list)

[ 0.08333333  0.58333333  1.08333333  1.58333333]


In [5]:
df(t_list)

array([ 0.99541022,  0.96769655,  0.93989703,  0.91220464])

In [7]:
(df(t_list) * 100)[-1]

91.220464002393399

In [9]:
np.sum(df(t_list) * 3.5)

13.353229526948304

In [6]:
(df(t_list) * 100)[-1] + np.sum(df(t_list) * 3.5)

104.57369352934171

In [7]:
df(t_list) * 3.5

array([ 3.48393576,  3.38693792,  3.28963961,  3.19271624])

In [8]:
np.sum(df(t_list) * 3.5)

13.353229526948304

In [9]:
dirty = df(t_list[-1]) * 100 + np.sum(df(t_list) * 3.5)

In [10]:
df(t_list)

array([ 0.99541022,  0.96769655,  0.93989703,  0.91220464])

In [11]:
df(t_list[0])

0.9954102183057264

In [12]:
accrue = 3.5 * 5/6 
print(accrue)

2.9166666666666665


In [13]:
dirty - accrue

101.65702686267504