In [2]:
import numpy as np

In [3]:
def r_c(t):
    return 0.02 + (t / (200 - t))

def df(t):
    return np.exp(-r_c(t) * t)

def gen_cf(t_list, cf):
    total_len = len(t_list)
    cf_list = [cf] * total_len
    cf_list[-1] += 100
    return cf_list

def gen_t_list(mat_in_m, interval_in_m):
    return np.arange((mat_in_m % interval_in_m)/12, (mat_in_m + 1)/12, interval_in_m / 12)[0:]

In [4]:
mat_in_m = 19
interval_in_m_list = [12, 6, 3]
annual_cpn = 4

for interval_in_m in interval_in_m_list:
    print("\n Calculating for cpn pay every %sm" % interval_in_m)
    t_list = gen_t_list(mat_in_m, interval_in_m)
    print("t_list in months:")
    print(t_list * 12)
    
    each_cpn = annual_cpn * (interval_in_m / 12)
    cf_list = gen_cf(t_list, each_cpn)
    print("cpn_list:")
    print(cf_list)
    
    df_list = df(t_list)
    print("df_list:")
    print(df_list)
    
    dirty = np.sum(df_list * cf_list)
    print("dirty_px = %s" % dirty)
    
    months_accrue = interval_in_m - (mat_in_m % interval_in_m)
    accrue =(months_accrue / 12) * each_cpn
    print("accrue = %s" % accrue)
    clean = dirty - accrue
    print("clean = %s" % clean)


 Calculating for cpn pay every 12m
t_list in months:
[  7.  19.]
cpn_list:
[4.0, 104.0]
df_list:
[ 0.98671599  0.95666556]
dirty_px = 103.440082368
accrue = 1.6666666666666667
clean = 101.773415702

 Calculating for cpn pay every 6m
t_list in months:
[  1.   7.  13.  19.]
cpn_list:
[2.0, 2.0, 2.0, 102.0]
df_list:
[ 0.99830004  0.98671599  0.97280981  0.95666556]
dirty_px = 103.495538978
accrue = 0.8333333333333334
clean = 102.662205645

 Calculating for cpn pay every 3m
t_list in months:
[  1.   4.   7.  10.  13.  16.  19.]
cpn_list:
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 101.0]
df_list:
[ 0.99830004  0.99280287  0.98671599  0.98004831  0.97280981  0.96501155
  0.95666556]
dirty_px = 102.518910298
accrue = 0.16666666666666666
clean = 102.352243631
