In [1]:
import numpy as np
from scipy.linalg import solve

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def gen_cf(t_list, cf):
    total_len = len(t_list)
    cf_list = [cf] * total_len
    cf_list[-1] += 100
    return cf_list

def gen_t_list(mat_in_m, interval_in_m):
    return np.arange((mat_in_m % interval_in_m)/12, (mat_in_m + 1)/12, interval_in_m / 12)[0:]

### Part i)

In [7]:
t_lists = [
    gen_t_list(11,6)
    , gen_t_list(17,6)
    , gen_t_list(23,12)
    , gen_t_list(23,6)
]

i=1
for t_list in t_lists:
    print("Bond %s's CF Dates in months:" % i)
    print(t_list * 12)
    i += 1

Bond 1's CF Dates in months:
[  5.  11.]
Bond 2's CF Dates in months:
[  5.  11.  17.]
Bond 3's CF Dates in months:
[ 11.  23.]
Bond 4's CF Dates in months:
[  5.  11.  17.  23.]


In [14]:
cf_list = [7/2, 8/2, 9.5, 11/2]
cf_lists = []

for t_list, cf in zip(t_lists, cf_list):
    cf_lists.append(gen_cf(t_list,cf))

i=1
for t_list, cf_list in zip(t_lists, cf_lists):
    print("Bond %s's CF Dates in months:" % i)
    print(t_list * 12)
    
    print("Bond %s's CF amounts in for each corresponding date:" % i)
    print(cf_list)
    print("\n")
    i += 1

Bond 1's CF Dates in months:
[  5.  11.]
Bond 1's CF amounts in for each corresponding date:
[3.5, 103.5]


Bond 2's CF Dates in months:
[  5.  11.  17.]
Bond 2's CF amounts in for each corresponding date:
[4.0, 4.0, 104.0]


Bond 3's CF Dates in months:
[ 11.  23.]
Bond 3's CF amounts in for each corresponding date:
[9.5, 109.5]


Bond 4's CF Dates in months:
[  5.  11.  17.  23.]
Bond 4's CF amounts in for each corresponding date:
[5.5, 5.5, 5.5, 105.5]




### Part ii)

The linear system of discount factors is then:

$$ 3.5df_5 + 103.5df_{11} = 104.45 $$
$$ 4df_5 + 4df_{11} + 104df_{17} = 108.50 $$
$$ 9.5df_{11} + 109.5df_{23} = 109.35 $$
$$ 5.5df_5 + 5.5df_{11} + 5.5df_{17} + 105.5df_{23} = 112.55 $$

In [16]:
# we can write it in matrix form:
A = np.array([
    [3.5,103.5,0,0]
    ,[4,4,104,0]
    ,[0,9.5,0,109.5]
    ,[5.5,5.5,5.5,105.5]
])
b = np.array([104.45,108.5,109.35,112.55])[:,None]

print("A=\n",A)
print("\nb=\n",b)

A=
 [[   3.5  103.5    0.     0. ]
 [   4.     4.   104.     0. ]
 [   0.     9.5    0.   109.5]
 [   5.5    5.5    5.5  105.5]]

b=
 [[ 104.45]
 [ 108.5 ]
 [ 109.35]
 [ 112.55]]


### Part iii)

In [18]:
x = solve(A,b)
print("discount factors for 5, 11, 17, 23 months are:")
print(x)

discount factors for 5, 11, 17, 23 months are:
[[ 0.98844324]
 [ 0.97575313]
 [ 0.96772322]
 [ 0.91397576]]
