In [1]:
import numpy as np

### Part i)

In [3]:
A = np.array([[4,-16,8,16],[0,6,-1,-2],[0,-16,12,16],[0,2,-1,2]])
print(A)

[[  4 -16   8  16]
 [  0   6  -1  -2]
 [  0 -16  12  16]
 [  0   2  -1   2]]


In [5]:
v1 = np.array([0,1,0,1])[:,None]
v2 = np.array([0,1,2,0])[:,None]
v3 = np.array([1,0,0,0])[:,None]
v4 = np.array([8,-1,8,-1])[:,None]

In [7]:
print(A.dot(v1))

[[0]
 [4]
 [0]
 [4]]


we can see Av1 = 4v1, verifying that v1 is an eiganvector to eiganvalue 4

In [8]:
print(A.dot(v2))

[[0]
 [4]
 [8]
 [0]]


we can see Av2 = 4v2, verifying that v2 is an eiganvector to eiganvalue 4

In [9]:
print(A.dot(v3))

[[4]
 [0]
 [0]
 [0]]


we can see Av3 = 4v3, verifying that v3 is an eiganvector to eiganvalue 4

Since lambda = 4 has multiplicity 3, and we found 3 linearly independant eiganvectors v1, v2, v3. These are all the linearly independant eiganvectors

In [10]:
print(A.dot(v4))

[[ 96]
 [-12]
 [ 96]
 [-12]]


we can see Av4 = 12v4, verifying that v4 is an eiganvector to eiganvalue 12

Since lambda = 12 has multiplicity 1, there is only 1 linearly independant eiganvector. Thus it is v4.

### Part ii)

In [11]:
B = np.array([[4,-1,0,1],[4,20,1,-8],[0,4,4,-4],[8,16,2,-4]])
print(B)

[[ 4 -1  0  1]
 [ 4 20  1 -8]
 [ 0  4  4 -4]
 [ 8 16  2 -4]]


In [12]:
w1 = np.array([-1,0,4,0])[:,None]
print(w1)

[[-1]
 [ 0]
 [ 4]
 [ 0]]


In [16]:
print(B.dot(w1))

[[-4]
 [ 0]
 [16]
 [ 0]]


w1 is an eiganvector corresponding to lambda = 4, from the write up, we also showed that w1 is the only linearly independant eiganvector corresponding to lambda = 4

In [15]:
w2 = np.array([0,1,0,1])[:,None]
print(w2)

[[0]
 [1]
 [0]
 [1]]


In [17]:
print(B.dot(w2))

[[ 0]
 [12]
 [ 0]
 [12]]


we can now see that w2 is an eigan vector corresponding to lambda = 12.