In [6]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import inv

In [3]:
A = np.array([[1,4],[-2,7]])
print(A)

[[ 1  4]
 [-2  7]]


In [8]:
V = np.array([[2,1],[1,1]])
V_inv = inv(V)
diag = np.array([[3,0],[0,5]])

In [9]:
V.dot(diag.dot(V_inv))

array([[ 1.,  4.],
       [-2.,  7.]])

In [29]:
A_orig = np.array([[1,4],[-2,7]])
A = A_orig
n = 12

for i in range(0,n-1):
    A = A.dot(A_orig)
print(A)

[[-243077743  487218368]
 [-243609184  487749809]]


In [30]:
print(2*(3**n) - (5**n))
print(2*(5**n)-2*(3**n))
print(3**n - 5**n)
print(2*(5**n) - 3**n)

-243077743
487218368
-243609184
487749809


In [31]:
-144 + 32 - 48 -96

-256

In [37]:
-144-96-16

-256

In [38]:
256/4

64.0