In [23]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

lib_path = r'/Users/rmfeng/jupyter/AC-FE/'
import sys
sys.path.append(lib_path)
import acfe_methods as am

from importlib import reload

In [39]:
mu = np.array([0.06, 0.12]).reshape(-1,1)
r = 0.02
mu_bar = mu - r

print(mu, "\n", r, "\n", mu_bar)

[[ 0.06]
 [ 0.12]] 
 0.02 
 [[ 0.04]
 [ 0.1 ]]


In [26]:
s1 = 0.15
s2 = 0.25
corr = np.array([[1, 0.3],
                 [0.3, 1]])
D = np.diag([s1,s2])
cov = np.matmul(np.matmul(D, corr), D)
cov

array([[ 0.0225 ,  0.01125],
       [ 0.01125,  0.0625 ]])

### Part i) Tangency Portfolio

In [27]:
w_tang = am.tangency_port(cov, mu_bar)
w_tang

array([[ 0.43307087],
       [ 0.56692913]])

### Part ii) mu = 8% min var port

In [33]:
w, wcash, sig = am.min_var_port(cov, mu, r, 0.08)
print("Allocation: asset1: %s, asset2: %s, cash: %s" % (w[0], w[1], wcash))
print("Standard Dev =", sig)

Allocation: asset1: [ 0.35106383], asset2: [ 0.45957447], cash: [[ 0.1893617]]
Standard Dev = [[ 0.1400133]]


### Part iii) mu = 15% min var port

In [34]:
w, wcash, sig = am.min_var_port(cov, mu, r, 0.15)
print("Allocation: asset1: %s, asset2: %s, cash: %s" % (w[0], w[1], wcash))
print("Standard Dev =", sig)

Allocation: asset1: [ 0.7606383], asset2: [ 0.99574468], cash: [[-0.75638298]]
Standard Dev = [[ 0.30336214]]


### Part iv) sig = 20% max ret port

In [40]:
w, wcash, mu_exp = am.max_ret_port(cov, mu, r, 0.2)
print("Allocation: asset1: %s, asset2: %s, cash: %s" % (w[0], w[1], wcash))
print("Expected Return =", mu_exp)

Allocation: asset1: [ 0.50147213], asset2: [ 0.6564726], cash: [[-0.15794473]]
Expected Return = [[ 0.10570615]]


### Part v) sig = 30% max ret port

In [41]:
w, wcash, mu_exp = am.max_ret_port(cov, mu, r, 0.3)
print("Allocation: asset1: %s, asset2: %s, cash: %s" % (w[0], w[1], wcash))
print("Expected Return =", mu_exp)

Allocation: asset1: [ 0.75220819], asset2: [ 0.9847089], cash: [[-0.73691709]]
Expected Return = [[ 0.14855922]]


### Part vi) - adjusting the min var mu=8% port

In [46]:
r = 0.02
w, wcash, sig = am.min_var_port(cov, mu, r, 0.08)
print("Before adj alloc: asset1: %s, asset2: %s, cash: %s" % (w[0], w[1], wcash))

r_new = 0.025
w_new, wcash_new, sig_new = am.min_var_port(cov, mu, r_new, 0.08)
print("After adj alloc: asset1: %s, asset2: %s, cash: %s" % (w_new[0], w_new[1], wcash_new))

Before adj alloc: asset1: [ 0.35106383], asset2: [ 0.45957447], cash: [[ 0.1893617]]
After adj alloc: asset1: [ 0.30042722], asset2: [ 0.46826366], cash: [[ 0.23130912]]


### Part vi) - adjusting the max ret sig = 20% port

In [48]:
r = 0.02
w, wcash, mu_exp = am.max_ret_port(cov, mu, r, 0.2)
print("Before adj alloc: asset1: %s, asset2: %s, cash: %s" % (w[0], w[1], wcash))

r_new = 0.025
w_new, wcash_new, mu_exp_new = am.max_ret_port(cov, mu, r_new, 0.2)
print("After adj alloc: asset1: %s, asset2: %s, cash: %s" % (w_new[0], w_new[1], wcash_new))

Before adj alloc: asset1: [ 0.50147213], asset2: [ 0.6564726], cash: [[-0.15794473]]
After adj alloc: asset1: [ 0.43705174], asset2: [ 0.68121472], cash: [[-0.11826646]]
