In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
lib_path = r'/Users/rmfeng/jupyter/AC-FE/'
import sys
sys.path.append(lib_path)
import acfe_methods as am
from importlib import reload

In [2]:
mu = np.array([0.051, 0.045, 0.068, 0.042]).reshape(-1,1)

cov_mat = np.array([[0.09, -0.01, -0.03, -0.02],
                   [-0.01, 0.0625, 0.02, -0.01],
                   [-0.03, 0.02, 0.1225, -0.015],
                   [-0.02, -0.01, -0.015, 0.0576]])
r = 0.015
mu_bar = mu - r

In [3]:
wt = am.tangency_port(cov_mat, mu_bar)

### Part i) Tangency port

In [4]:
print("Tangency Asset Alloc:")
print(wt)

Tangency Asset Alloc:
[[ 0.2846145 ]
 [ 0.17572449]
 [ 0.21253932]
 [ 0.32712169]]


In [14]:
exp_return = mu.transpose().dot(wt)
print("Tangency Portfolio Return:")
print(exp_return)

Tangency Portfolio Return:
[[ 0.05061473]]


In [15]:
port_std = np.sqrt(wt.transpose().dot(cov_mat).dot(wt))
print("Tangency Portfolio Std:")
print(port_std)

Tangency Portfolio Std:
[[ 0.10403063]]


In [17]:
sharpe = (exp_return - r) / port_std
print("Tangency Portfolio Sharpe:")
print(sharpe)

Tangency Portfolio Sharpe:
[[ 0.34234846]]


### Part ii) 5% expected return min var portfolio

In [18]:
w, wcash, sig_min = am.min_var_port(cov_mat, mu, r, 0.05)

In [20]:
print("Asset Alloc:")
print(w)
print("Cash Alloc:")
print(wcash)
print("Standard Dev:")
print(sig_min)
print("Sharpe:")
print((0.05 - r) / sig_min)

Asset Alloc:
[[ 0.27970192]
 [ 0.17269141]
 [ 0.20887079]
 [ 0.32147542]]
Cash Alloc:
[[ 0.01726045]]
Standard Dev:
[[ 0.10223501]]
Sharpe:
[[ 0.34234846]]


### Part iii) 29% std max return portfolio

In [21]:
w, wcash, exp_ret = am.max_ret_port(cov_mat, mu, r, 0.29)

In [22]:
print("Asset Alloc:")
print(w)
print("Cash Alloc:")
print(wcash)
print("Expected Return:")
print(exp_ret)
print("Sharpe:")
print((exp_ret - r) / 0.29)

Asset Alloc:
[[ 0.79340291]
 [ 0.48985672]
 [ 0.59248322]
 [ 0.91189769]]
Cash Alloc:
[[-1.78764054]]
Expected Return:
[[ 0.11428105]]
Sharpe:
[[ 0.34234846]]


### Part iv) Fully Invested portfolio

In [34]:
wf = am.fully_invested_port(cov_mat)
print("Asset Alloc:")
print(wf)

Asset Alloc:
[[ 0.27131101]
 [ 0.21541792]
 [ 0.15951476]
 [ 0.35375631]]


In [35]:
exp_full = wf.transpose().dot(mu_bar) + r
sig_full = np.sqrt(wf.transpose().dot(cov_mat).dot(wf))
print("Expected Return:")
print(exp_full)
print("Standard Dev:")
print(sig_full)
print("Sharpe:")
print((exp_full - r)/sig_full)

Expected Return:
[[ 0.04923544]]
Standard Dev:
[[ 0.10199629]]
Sharpe:
[[ 0.33565376]]
