In [1]:
import numpy as np

In [2]:
B = np.array([[2,-1,0,0],
             [-1,2,-1,0],
             [0,-1,2,-1],
             [0,0,-1,2]])

In [3]:
B

array([[ 2, -1,  0,  0],
       [-1,  2, -1,  0],
       [ 0, -1,  2, -1],
       [ 0,  0, -1,  2]])

In [5]:
C = np.linalg.cholesky(B)

In [6]:
C

array([[ 1.41421356,  0.        ,  0.        ,  0.        ],
       [-0.70710678,  1.22474487,  0.        ,  0.        ],
       [ 0.        , -0.81649658,  1.15470054,  0.        ],
       [ 0.        ,  0.        , -0.8660254 ,  1.11803399]])

In [16]:
D = np.append(C, [[0],[0],[0],[1]], axis=1)
E = np.array([[0,0,0,0,0],
             [0,0,0,0,0],
             [0,0,0,0,0],
             [0,0,0,-np.sqrt(1.25)+np.sqrt(0.25),0]])
F = D + E
F

array([[ 1.41421356,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.70710678,  1.22474487,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.81649658,  1.15470054,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.8660254 ,  0.5       ,  1.        ]])

In [17]:
np.matmul(F,F.transpose())

array([[ 2., -1.,  0.,  0.],
       [-1.,  2., -1.,  0.],
       [ 0., -1.,  2., -1.],
       [ 0.,  0., -1.,  2.]])

In [18]:
C = np.array([[np.sqrt(2),0,0,0,0],
             [-np.sqrt(2)/2, np.sqrt(3/2),0,0,0],
             [0, -np.sqrt(2/3), np.sqrt(4/3),0,0],
             [0,0,-np.sqrt(3/4),0.5,1]])

In [19]:
C

array([[ 1.41421356,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.70710678,  1.22474487,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.81649658,  1.15470054,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.8660254 ,  0.5       ,  1.        ]])

In [20]:
np.matmul(C,C.transpose())

array([[ 2., -1.,  0.,  0.],
       [-1.,  2., -1.,  0.],
       [ 0., -1.,  2., -1.],
       [ 0.,  0., -1.,  2.]])