In [12]:
import numpy as np
from scipy.linalg import solve

In [2]:
A = np.array([0.25, 1, -0.5, 0 , -1])
B = np.array([-0.5, -1, -0.25, 0.5, 0.75])
C = np.array([1.5, 1.25, 2, 0.75, 1.5])

In [8]:
Ab = A - np.mean(A)
Bb = B - np.mean(B)
Cb = C - np.mean(C)

In [9]:
Tb = np.array([Ab,Bb,Cb]).transpose()
Tb

array([[ 0.3 , -0.4 ,  0.1 ],
       [ 1.05, -0.9 , -0.15],
       [-0.45, -0.15,  0.6 ],
       [ 0.05,  0.6 , -0.65],
       [-0.95,  0.85,  0.1 ]])

In [11]:
cov = (1 / 4) * np.matmul(Tb.transpose(), Tb)
cov

array([[ 0.575  , -0.44375, -0.13125],
       [-0.44375,  0.51875, -0.075  ],
       [-0.13125, -0.075  ,  0.20625]])

In [17]:
c1 = cov[0,:]
c1

array([ 0.575  , -0.44375, -0.13125])

In [19]:
c2 = cov[1,:]
c2

array([-0.44375,  0.51875, -0.075  ])

In [20]:
c3 = cov[2,:]
c3

array([-0.13125, -0.075  ,  0.20625])

In [21]:
c1+c2

array([ 0.13125,  0.075  , -0.20625])