In [1]:
import numpy as np
from scipy.linalg import solve

In [2]:
# another approach
def f_x(x):
    return (2 * np.exp(-x) + x * np.exp(-x))

def generate_A_and_b(n):
    """ n is number of intervals """
    h = 1 / n
    # first row
    A = np.array([[1] + [0]*(n-2)])
    b = np.array([[2-h]])
    
    # 2nd row
    A = np.append(A, [[h**2-2, 1+h] + [0]*(n-3)], axis=0)
    b = np.append(b, [[(h-1)*2]], axis=0)
    # other rows
    for i in range(2, n-1):
        A = np.append(A, [[0]*(i-2) + [1-h, h**2-2, 1+h] + [0]*(n-3-(i-2)-1)], axis=0)
        b = np.append(b, [[0]], axis=0)
    return A, b

def generate_real_soln(n):
    h = 1 / n
    y = np.array([])
    for i in range(1, n):
        y = np.append(y, f_x(i*h))
    return y.reshape(-1,1)

In [3]:
i_list = np.array([3,4,5,6])
n_list = 2**i_list
n_list

array([ 8, 16, 32, 64])

In [4]:
dict_error = {}
prev_error = 0
for n in n_list:
    print("\nComputing estimated and real values for n=%s" % n)
    A, b = generate_A_and_b(n)
    y = solve(A,b)
    y_real = generate_real_soln(n)
    print("estimated - real:")
    print(np.append(y,y_real,axis=1))
    
    # measuring error
    max_error = np.max(np.abs(y-y_real))
    if prev_error != 0:
        error_reduction = prev_error / max_error
    else:
        error_reduction = 'N/A'
    prev_error = max_error
    
    dict_error[n] = (max_error, error_reduction)


Computing estimated and real values for n=8
estimated - real:
[[ 1.875       1.87530592]
 [ 1.75173611  1.75230176]
 [ 1.63153453  1.63231204]
 [ 1.51538421  1.51632665]
 [ 1.40399807  1.40506125]
 [ 1.29786443  1.29900802]
 [ 1.19729015  1.19847831]]

Computing estimated and real values for n=16
estimated - real:
[[ 1.9375      1.93753944]
 [ 1.87522978  1.87530592]
 [ 1.81339124  1.8135012 ]
 [ 1.75216094  1.75230176]
 [ 1.69169244  1.69186114]
 [ 1.63211843  1.63231204]
 [ 1.57355268  1.57376828]
 [ 1.5160919   1.51632665]
 [ 1.45981735  1.46006849]
 [ 1.40479636  1.40506125]
 [ 1.35108373  1.35135987]
 [ 1.29872302  1.29900802]
 [ 1.24774767  1.24803931]
 [ 1.19818212  1.19847831]
 [ 1.15004272  1.15034153]]

Computing estimated and real values for n=32
estimated - real:
[[ 1.96875     1.96875501]
 [ 1.93752959  1.93753944]
 [ 1.90636655  1.90638107]
 [ 1.8752869   1.87530592]
 [ 1.84431503  1.84433836]
 [ 1.81347374  1.8135012 ]
 [ 1.7827843   1.78281571]
 [ 1.75226659  1.7523017

In [5]:
dict_error

{8: (0.0011881588416675637, 'N/A'),
 16: (0.00029880782406688233, 3.9763310929958027),
 32: (7.4809787007357187e-05, 3.9942343912501181),
 64: (1.8709109184555928e-05, 3.9985755745715288)}